### ISSUE TITLE
Como usarlo en Reactive forms

### ISSUE THREAD

**Issue by niesteszeck** [platanus/ng2-rut#14]
Hola,

Al usar el rutValidator en reactive form, con FormBuilder, como obtineen la funcion a colocar en el arreglo?
yo coloqué esto, alguna otra opción recomendada?

```
....
aboutPerson: this.fb.group({
        rut: ['', [Validators.required, validateRutFactory(rutValidate)]],
....
```

**Comment by niesteszeck** [comment]
Disculpen la pregunta, con el Pull request #13 me di cuenta que estaba preguntando leseras.

**Comment by llekn** [comment]
@niesteszeck hey! no hay problema, gracias de todas maneras por la preocupación! 👍
