### ISSUE TITLE
Error 404 al importar

### ISSUE THREAD

**Issue by migb** [platanus/ng2-rut#16]
Hola, no me esposible utilizar el modulo.
 Me arroja este error: GET http://localhost:5555/node_modules/ng2-rut.js 404 (Not Found)

el directorio esta dentro de los módulos de nodejs.

import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { Ng2Rut } from 'ng2-rut';

@NgModule({
  imports: [BrowserModule,
    ReactiveFormsModule,
    Ng2Rut,
    ChartsModule,
    ...

**Comment by llekn** [comment]
Hola @migb .

Estoy reviviendo esta librería.

¿Nos podrías confirmar si pudiste resolver el error o, si es que persiste, qué versión de Angular estás usando (e idealmente código para reproducir el error)?

**Comment by llekn** [comment]
Ya que no tuve respuesta voy a cerrar este Issue. Feliz de reabrirlo si aparecen nuevos datos
