### ISSUE TITLE
Formato Rut

### ISSUE THREAD

**Issue by cartapia** [platanus/ng2-rut#20]
Hola,
He probado varios ruts y los  que comienzan en 13 no están funcionando correctamente. Por ejemplo:
Al ingresar 13656649  me lo valida correctamente a pesar de que falta el digito verificador 0.

Saludos

**Comment by rosses** [comment]
@cartapia  el rut 1.365.664-9 es válido. No es un problema del algoritmo de validación.

**Comment by bunzli** [comment]
Así es, tal como dice @rosses , al ingresar 13656649, el validador lo interpreta como 1.365.664-9 que resulta ser válido. Algunos ruts tiene esa "mala suerte".
