### ISSUE TITLE
Hello ! Se sigue manteniendo este repo ?

### ISSUE THREAD

**Issue by danielsotopino** [platanus/ng2-rut#25]
Tengo problemas con Angular9 y la librería por que se deprecó "Renderer" a "Renderer2"
Si no lo están actualizando puedo armar un ng9-rut ? :P

**Comment by joacoseco** [comment]
yo igual he intentado usar este mismo repo, pero no logro hacer que funcione

**Comment by danielsotopino** [comment]
> yo igual he intentado usar este mismo repo, pero no logro hacer que funcione

hice una copia de este proyecto y actualicé la librería
https://github.com/landscapedotcl/ng9-rut

**Comment by joacoseco** [comment]
> > yo igual he intentado usar este mismo repo, pero no logro hacer que funcione
> 
> hice una copia de este proyecto y actualicé la librería
> https://github.com/landscapedotcl/ng9-rut

Se puede utilizar igual para Angular 8? tengo este problema
/node_modules/ng9-rut/ng9-rut"' has no exported member 'Ng9Rut'

**Comment by ghost** [comment]
> > > yo igual he intentado usar este mismo repo, pero no logro hacer que funcione
> > 
> > 
> > hice una copia de este proyecto y actualicé la librería
> > https://github.com/landscapedotcl/ng9-rut
> 
> Se puede utilizar igual para Angular 8? tengo este problema
> /node_modules/ng9-rut/ng9-rut"' has no exported member 'Ng9Rut'

Yo utilizo el actual para Angular8 sin ningun problema.

**Comment by ghost** [comment]
> > yo igual he intentado usar este mismo repo, pero no logro hacer que funcione
> 
> hice una copia de este proyecto y actualicé la librería
> https://github.com/landscapedotcl/ng9-rut

Maestro.
