### ISSUE TITLE
update a angular 9: no exported member 'Renderer'. Did you mean 'Renderer2'?

### ISSUE THREAD

**Issue by crsepulv** [platanus/ng2-rut#28]
Hice el update a angular 9 y me di[o el siguiente error:
```
ERROR in node_modules/ng2-rut/dist/rut-value-accessor.d.ts:2:22 - error TS2724: Module '"../../@angular/core/core"' has
no exported member 'Renderer'. Did you mean 'Renderer2'?

2 import { ElementRef, Renderer } from '@angular/core';
                       ~~~~~~~~

  node_modules/@angular/core/core.d.ts:5740:31
    5740 export declare abstract class Renderer2 {
                                       ~~~~~~~~~
    'Renderer2' is declared here.
```
Modifique el archivo y cambie render por render2 y se arreglo, no se como hacer un PR que permita compatibilidad con versiones anteriores y angular 9.

**Comment by llekn** [comment]
Pienso que a estas alturas no es posible/deseable mantener compatibilidad al mismo tiempo con las versiones que usan sólo `Renderer` y sólo `Renderer2`.

Creo que lo mejor sería que hagas el PR de todas formas para que se incluya en una nueva versión con breaking changes (1.0.0?). Eso sí, habría que actualizar las dependencias (idealmente con la versión más vieja posible que soporte `Renderer2`, creo que es Angular 4) para representar las nuevas dependencias y que pasen los tests.

**Comment by tlarrain** [comment]
en el PR #27 está el update, falta que alguien lo incorpore
